### ISSUE TITLE
Validating the example throws an error

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/stats-models#22]
It is expecting a `Contrasts` property for `DummyContrasts` and I think that the latest discussion in the spec is to make this not required in case people want to implicitly run a contrasts on all conditions. Bad idea at lower levels but may make sense at higher levels.

https://github.com/bids-standard/stats-models/blob/main/specification/examples/model-example_smdl.json

```
{
  "keyword": "required",
  "dataPath": ".Nodes[1].DummyContrasts",
  "schemaPath": "#/definitions/DummyContrasts/required",
  "params": {
    "missingProperty": "Contrasts"
  },
  "message": "should have required property 'Contrasts'"
}
```

**Comment by effigies** [comment]
Yes. Need to discuss: https://github.com/bids-standard/stats-models/pull/11

Didn't seem worth editing and then including the revert in that PR.

**Comment by Remi-Gau** [comment]
Retried and the error is not there anymore.
So this got fixed but I can't recall when.
