### ISSUE TITLE
enforce a line length in the model file

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/stats-models#23]
https://github.com/bids-standard/stats-models/blob/main/bsmschema/bsmschema/models.py

No having to horizontal scroll would be nice when code reviewing this file.

**Comment by effigies** [comment]
Agreed, it was a pretty quick copy-paste job. Happy to take a PR.

But it is all rendered here and will be a better place to review it: https://bids-standard.github.io/stats-models/reference.html

**Comment by Remi-Gau** [comment]
will close for now

let's get back to this if it gets necessary
