### ISSUE TITLE
Create static website

### ISSUE THREAD

**Issue by adelavega** [bids-standard/stats-models#3]
Most likely a Jupyter Book, but also considering other static website builders.

Main features we want that Jupyter Book is good at:

- Markdown writing
- Bookmarks through out document
- PDF generation

Other features that Jupyter Book may not be good at:
- Model zoo graphical display (i.e. examples)
- Including the validator as part of the website

**Comment by Remi-Gau** [comment]
> Other features that Jupyter Book may not be good at:
> 
>     * Model zoo graphical display (i.e. examples)
> 
>     * Including the validator as part of the website

do we HAVE to bring everything under a single website?

**Comment by adelavega** [comment]
Closed by #6
