### ISSUE TITLE
RFC: Should software drop the outer list?

### ISSUE THREAD

**Issue by effigies** [bids-standard/stats-models#34]
From [Model.Software](https://bids-standard.github.io/stats-models/_autosummary/bsmschema.models.Model.html#bsmschema.models.Model.Software)

> field `Software`: `Optional[List[Dict[str, Dict[str, Any]]]]`
> This section allows one to specify any software-specific estimation parameters. Each value in the list is an object, with the key being the name of the software package (FSL, SPM, etc.), and the value being an object containing software-specific parameters. The BIDS-Model spec makes no attempt to control the vocabulary available for use in any particular software package; we expect that the developers of each package will, over time, fill in these specifications.

Should the type instead be `Optional[Dict[str, Dict[str, Any]]]` and the text updated to:

> This section allows one to specify any software-specific estimation parameters. Each key in the object is the name of the software package (FSL, SPM, etc.), and the value is an object containing parameters specific to that software. The BIDS-Model spec makes no attempt to control the vocabulary available for use in any particular software package; we expect that the developers of each package will, over time, fill in these specifications.

**Comment by effigies** [comment]
To be clear, this would change:
```JSON
[
  {"FSL": {"fslparam": "val1"}},
  {"SPM": {"spmparam": "val2"}}
]
```

To:

```JSON
{
  "FSL": {"fslparam": "val1"},
  "SPM": {"spmparam": "val2"}
}
```

**Comment by Remi-Gau** [comment]
Agreed: fewer curly braces would be good.
